# Generated by Django 3.2 on 2023-08-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_comment_comment_like'),
        ('cart', '0002_rename_basket_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.variants'),
        ),
    ]
