# Generated by Django 3.2 on 2023-08-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
