# Generated by Django 3.2 on 2023-08-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_auto_20230812_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcolor'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productsize'),
        ),
    ]
