# Generated by Django 3.2 on 2023-08-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_auto_20230827_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
