# Generated by Django 3.2 on 2023-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_product_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
